<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/users/login.proto

namespace Login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>login.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     */
    protected $pwd = '';
    /**
     * Generated from protobuf field <code>string stime = 3;</code>
     */
    protected $stime = '';
    /**
     * Generated from protobuf field <code>string sign = 4;</code>
     */
    protected $sign = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $pwd
     *     @type string $stime
     *     @type string $sign
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pb\Users\Login::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     * @return string
     */
    public function getPwd()
    {
        return $this->pwd;
    }

    /**
     * Generated from protobuf field <code>string pwd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPwd($var)
    {
        GPBUtil::checkString($var, True);
        $this->pwd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stime = 3;</code>
     * @return string
     */
    public function getStime()
    {
        return $this->stime;
    }

    /**
     * Generated from protobuf field <code>string stime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStime($var)
    {
        GPBUtil::checkString($var, True);
        $this->stime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sign = 4;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * Generated from protobuf field <code>string sign = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

}

